### PR TITLE
Fixed Caller Line info and file info

### PR DESCRIPTION
**Pull request by BublilDaniel**
hi 
as mention here #9 
I just wanted the file name and line number so I ended up doing something like that.

Thanks!

### CODE REVIEW

**Comment by pmetz-steelcase** [comment]
Hi Daniel, 
I think the line number of the source is a build in feature in Serilog that can be specified it in the pattern (or do I miss something?)
For the file name, there is a flag in the constructor

See example in the console demo dev branch [dev_basedOn120]
( https://github.com/pmetz-steelcase/Serilog.Enrichers.WithCaller/tree/dev_basedOn120 )
...
Log.Logger = new LoggerConfiguration()
    .Enrich.WithCaller(true)
    .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message} (at {Caller}){NewLine}{Exception}")
    .MinimumLevel.Debug()
    .CreateLogger();
 ...
 
Cheers, Peter

**Comment by jasonswearingen** [comment]
note that you need to pass the includeFileInfo=true or otherwise create the `CallerEnricher` yourself to get the line number.

**Comment by pmetz-steelcase** [comment]
@BublilDaniel 
Hi, also like @jasonswearingen mentioned, I think adding the lines
```  
logEvent.AddPropertyIfAbsent(new LogEventProperty("CallerLineNo",   new ScalarValue(frame.GetFileLineNumber())));  
logEvent.AddPropertyIfAbsent(new LogEventProperty("CallerFileName", new ScalarValue(Path.GetFileName(callerFileName))));  
```
                        
would just made it twice the same thing.
Did you try to follow suggestion from @jasonswearingen ?

Regards

**Comment by 0xced** [comment]
Pull request #12 addresses this concern in a more general way by providing **structured** information about the caller.

And with the [Serilog.Expressions](https://github.com/serilog/serilog-expressions) package it becomes trivial to format the caller information as you like. For example, to use the file path and line number.

```cs
using Serilog;
using Serilog.Enrichers.WithCaller;
using Serilog.Templates;

var logger = new LoggerConfiguration()
    .WriteTo.Console(new ExpressionTemplate("[{@t:HH:mm:ss} {@l}] {CallerInfo.File.Path}:{CallerInfo.File.Line}\n{@m:lj}"))
    .Enrich.WithCaller(includeFileInfo: true)
    .CreateLogger();

logger.Information("Hello World!");
```

Running this code produces the following output.
```
[14:34:32 Information] /Absolute/Path/To/SampleApp/Program.cs:10
  Hello World!
```

**Comment by pmetz-steelcase** [comment]
sorry, I have to close my account here
please continue with https://github.com/pm4net/serilog-enrichers-callerinfo

**Comment by ppmetz** [comment]
hi, so the source file path is in the pdb
I do use that configuration in project.csproj 

<PropertyGroup>
...
<AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
<PathMap>$(AppOutputBase)=$(SolutionName)</PathMap>
...
</PropertyGroup>

that's derived from example here:
https://www.tabsoverspaces.com/233662-changing-paths-in-pdb-files-for-source-files-and-pdb-file-path-in-dll-as-well

**Pull request closed without merging**
